// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itotbnmuonmmjonenwbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0b3Ribm11b25tbWpvbmVud2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzODgyNzEsImV4cCI6MjA3NTk2NDI3MX0.T3saYt6nQpCFTd6wm5hdakj2ESQYBZGJmhVhoGTLD3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});